In [15]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
a = [[1,2,3],
    [4,5,6,],
    [7,8,9,]]
b = [[1,2,3],
    [4,5,6,],
    [7,8,9,]]
sum_m = np.empty((3,3))
for i in range(len(a)):
    for j in range(len(a[0])):
        sum_m[i][j] = a[i][j]+b[i][j]

print(sum_m)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [17]:

#2. Write a Python Program to Multiply Two Matrices?

Umul  =  np.zeros((3,3))

for i in range(len(a)):
    for j in range(len(a[0])):
        for k in range(len(b)):
            Umul[i][j] += a[i][k]*b[k][i]

print(Umul)

[[ 30.  30.  30.]
 [ 81.  81.  81.]
 [150. 150. 150.]]


In [21]:

#3. Write a Python Program to Transpose a Matrix?
b = np.empty((3,3))
def trans(A):
    for i in range(len(a)):
        for j in range(len(a[0])):
            b[i][j] = A[j][i]
    return b



trans(a)


array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [25]:

#4. Write a Python Program to Sort Words in Alphabetic Order?

print('input a string')

A  = str(input())

b = A.split()

a=''

b.sort()

for word in b:
    a = a+" "+ word

print(a)


input a string
hi how are you
 are hi how you


In [27]:

#5. Write a Python Program to Remove Punctuation From a String?

import re

print('input a string')

A  = str(input())

b = re.sub(r'[^\w\s]','',A)

print(b)





input a string
hi ! HOW ARE YP=OU?
hi  HOW ARE YPOU
